language: ruby

matrix:
  fast_finish: true
  include:
    - env: NEO4J_VERSION="3.0.6"
    - env: NEO4J_VERSION="2.3.9"
    - env: NEO4J_VERSION="2.3.sss9"
    - env: NEO4J_VERSION="2.dd3.9"
  allow_failures:
    - env: NEO4J_VERSION="2.3.sss9"
    - env: NEO4J_VERSION="2.dd3.9"

install:
- if [ "${NEO4J_VERSION}" = "3.0.6" ]; then sleep 60; fi
- if [ "${NEO4J_VERSION}" = "2.3.9" ]; then sleep 10; fi
- if [ "${NEO4J_VERSION}" = "2.3.sss9" ]; then sleep 180; fi
- if [ "${NEO4J_VERSION}" = "2.dd3.9" ]; then sleep 200; fi
- travis_terminate 1
